# This workflow deploys a React+Vite application to Azure Static Webapps using the workflow specified in
# the `react-vite-test-release-push.yml` template.
# the workflow allows the creation of different deployment environments and handles environments for pull requests.
# To add different versions of environment variables to the Azure Static WebApp, go to your repository settings,
# navigate to "Environments" and add respective environment variables and environment secrets to each environment.
# You might need to create the environments ("production" and "development") first if they do not exist yet.

name: Deploy to Azure Static Web Apps
on:
  push:
    branches:
      # - main # Uncomment this line to deploy on push to main branch
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "." # location of your client code
  APP_ARTIFACT_LOCATION: "dist" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app
  AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }} # (optional) secret for private npm registry access

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  determine_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      deploy_condition: ${{ steps.env.outputs.deploy_condition }}
    steps:
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "deploy_condition=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" || [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" != "closed" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "deploy_condition=true" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "deploy_condition=false" >> $GITHUB_OUTPUT
          fi
  

  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    needs: determine_environment
    if: needs.determine_environment.outputs.deploy_condition

    permissions:
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs

    outputs:
      static_web_app_url: ${{ steps.azure_deploy.outputs.static_web_app_url }}

    environment:
      name: ${{ needs.determine_environment.outputs.environment }}
      url: ${{ "${{ github.event_name }}" != "pull_request" || needs.azure_deploy.outputs.static_web_app_url }}


    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Optionally set up .npmrc for private npm registry access
      - name: Setup .npmrc
        run: |
          echo "//pkgs.dev.azure.com/serapion/nova/_packaging/nova/npm/registry/:_authToken=${{ env.AZURE_DEVOPS_TOKEN }}" > ${{ env.APP_LOCATION }}/.npmrc
          echo "registry=https://pkgs.dev.azure.com/serapion/nova/_packaging/nova/npm/registry/" >> ${{ env.APP_LOCATION }}/.npmrc

      - name: Build And Deploy
        id: azure_deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          skip_api_build: true
          production_branch: "main"
        env:
          # TODO: Replace these with your actual environment variables or secrets
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}
          VITE_AUTH0_DOMAIN: ${{ vars.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ vars.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ vars.VITE_AUTH0_AUDIENCE }}
          # Add any additional environment variables needed for your app here

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
